#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID    : "662793765491"
    ECR_REPO_NAME     : "webapp1"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 662793765491.dkr.ecr.eu-central-1.amazonaws.com
      - git clone https://github.com/abtagir/codebuild-demo.git
      - cd codebuild-demo
      - COMMIT_ID=$(git rev-parse --short HEAD)
      - echo "Commit ID is $COMMIT_ID"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"webapp1","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $ECR_REPO_NAME $ECR_IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
  discard-paths: yes
  base-directory: codebuild-demo
